sonar.projectKey=AccountingApp
# sonar.host.url=http://127.0.0.1:9000
# sonar.token=REPLACE_WITH_ENV_VARIABLE

# Only scan real source code
# sonar.sources=app,resources/js,resources/views,routes

# Exclude dependencies & generated files
# sonar.exclusions=**/node_modules/**,\
# **/vendor/**,\
# **/public/build/**,\
# **/bootstrap/cache/**,\
# **/storage/**,\
# **/dist/**,\
# **/build/**,\
# **/coverage/**,\
# **/*.min.js,\
# **/*.min.css

# # (Optional but recommended)
# sonar.tests=tests